---
title: Fonds de cartes
ident: ''
description: Fonds de cartes IGN, OpenStreetMap, etc.
metadata_url: ''
type: folder
children:

  - title: Plan IGN
    ident: plan_ign
    description: >-
      Fond cartographique proposé par l’IGN.
    metadata_url: https://www.geoportail.gouv.fr/actualites/plan-ign-la-nouvelle-reference-cartographique
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/png&layers=GEOGRAPHICALGRIDSYSTEMS.PLANIGNV2&styles=normal&tileMatrixSet=PM&tilePixelRatio=0&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
      provider: wms

  - title: OpenStreetMap - Style Google Maps
    ident: openstreetmap
    description: >-
      Fond de plan OpenStreetMap élaboré par GéoGrandEst - OSM style Google Maps
    metadata_url: https://www.datagrandest.fr/geonetwork/srv/fre/catalog.search#/metadata/FR-200052264-GGE-OSM
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/png&layers=relief&styles&tilePixelRatio=0&url=https://osm.datagrandest.fr/mapcache
      provider: wms

  - title: ADMINEXPRESS COG
    ident: admin_express
    description: >-
      Délimitations administratives française qui varient en fonction du zoom sur la carte. 
      Contient les Régions, Départements, EPCI, Métropoles, Communes.
    metadata_url: https://geoservices.ign.fr/adminexpress
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/png&layers=ADMINEXPRESS-COG.LATEST&styles=normal&tileMatrixSet=PM&tilePixelRatio=0&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
      provider: wms

  - title: PLEIADES 2022
    ident: pleiades
    description: >-
      Mosaïque d’orthoimages résultant d’un traitement massivement automatisé pour minimiser les délais de production.
    metadata_url: https://www.geoportail.gouv.fr/donnees/ortho-express-2022
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/png&layers=ORTHOIMAGERY.ORTHO-SAT.PLEIADES.2022&styles=normal&tileMatrixSet=PM&tilePixelRatio=0&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
      provider: wms

  - title: SPOT 2023
    ident: spot
    description: >-
      Mosaïque d’orthoimages résultant d’un traitement massivement automatisé pour minimiser les délais de production.
    metadata_url: ''
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/jpeg&layers=ORTHOIMAGERY.ORTHO-SAT.SPOT.2023&styles=normal&tileMatrixSet=PM&tilePixelRatio=0&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
      provider: wms
