---
title: Image aérienne historique (IGN)
ident: image_historique
description: Données Ortho® anciennes éditions et historiques.
metadata_url: https://geoservices.ign.fr/documentation/donnees/ortho/bdorthohisto
type: folder
children:

  - title: Photographies aériennes 2020
    ident: ortho_historique_2020
    description: ''
    metadata_url: ''
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/jpeg&layers=ORTHOIMAGERY.ORTHOPHOTOS2020&styles=normal&tileMatrixSet=PM&tilePixelRatio=0&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
      provider: wms

  - title: Photographies aériennes 2019
    ident: ortho_historique_2019
    description: ''
    metadata_url: ''
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/jpeg&layers=ORTHOIMAGERY.ORTHOPHOTOS2019&styles=normal&tileMatrixSet=PM&tilePixelRatio=0&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
      provider: wms

  - title: Photographies aériennes 2018
    ident: ortho_historique_2018
    description: ''
    metadata_url: ''
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/jpeg&layers=ORTHOIMAGERY.ORTHOPHOTOS2018&styles=normal&tileMatrixSet=PM&tilePixelRatio=0&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
      provider: wms

  - title: Photographies aériennes 2017
    ident: ortho_historique_2017
    description: ''
    metadata_url: ''
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/jpeg&layers=ORTHOIMAGERY.ORTHOPHOTOS2017&styles=normal&tileMatrixSet=PM&tilePixelRatio=0&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
      provider: wms

  - title: Photographies aériennes 2016
    ident: ortho_historique_2016
    description: ''
    metadata_url: ''
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/jpeg&layers=ORTHOIMAGERY.ORTHOPHOTOS2016&styles=normal&tileMatrixSet=PM&tilePixelRatio=0&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
      provider: wms

  - title: Photographies aériennes 2015
    ident: ortho_historique_2015
    description: ''
    metadata_url: ''
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/jpeg&layers=ORTHOIMAGERY.ORTHOPHOTOS2015&styles=normal&tileMatrixSet=PM&tilePixelRatio=0&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
      provider: wms

  - title: Photographies aériennes 2014
    ident: ortho_historique_2014
    description: ''
    metadata_url: ''
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/jpeg&layers=ORTHOIMAGERY.ORTHOPHOTOS2014&styles=normal&tileMatrixSet=PM&tilePixelRatio=0&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
      provider: wms

  - title: Photographies aériennes 2013
    ident: ortho_historique_2013
    description: ''
    metadata_url: ''
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/jpeg&layers=ORTHOIMAGERY.ORTHOPHOTOS2013&styles=normal&tileMatrixSet=PM&tilePixelRatio=0&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
      provider: wms

  - title: Photographies aériennes 2012
    ident: ortho_historique_2012
    description: ''
    metadata_url: ''
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/jpeg&layers=ORTHOIMAGERY.ORTHOPHOTOS2012&styles=normal&tileMatrixSet=PM&tilePixelRatio=0&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
      provider: wms

  - title: Photographies aériennes 2011
    ident: ortho_historique_2011
    description: ''
    metadata_url: ''
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/jpeg&layers=ORTHOIMAGERY.ORTHOPHOTOS2011&styles=normal&tileMatrixSet=PM&tilePixelRatio=0&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
      provider: wms

  - title: Photographies aériennes 2010
    ident: ortho_historique_2010
    description: ''
    metadata_url: ''
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/jpeg&layers=ORTHOIMAGERY.ORTHOPHOTOS2010&styles=normal&tileMatrixSet=PM&tilePixelRatio=0&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
      provider: wms

  - title: Photographies aériennes 2009
    ident: ortho_historique_2009
    description: ''
    metadata_url: ''
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/jpeg&layers=ORTHOIMAGERY.ORTHOPHOTOS2009&styles=normal&tileMatrixSet=PM&tilePixelRatio=0&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
      provider: wms

  - title: Photographies aériennes 2008
    ident: ortho_historique_2008
    description: ''
    metadata_url: ''
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/jpeg&layers=ORTHOIMAGERY.ORTHOPHOTOS2008&styles=normal&tileMatrixSet=PM&tilePixelRatio=0&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
      provider: wms

  - title: Photographies aériennes 2007
    ident: ortho_historique_2007
    description: ''
    metadata_url: ''
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/jpeg&layers=ORTHOIMAGERY.ORTHOPHOTOS2007&styles=normal&tileMatrixSet=PM&tilePixelRatio=0&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
      provider: wms

  - title: Photographies aériennes 2006
    ident: ortho_historique_2006
    description: ''
    metadata_url: ''
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/jpeg&layers=ORTHOIMAGERY.ORTHOPHOTOS2006&styles=normal&tileMatrixSet=PM&tilePixelRatio=0&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
      provider: wms

  - title: Photographies aériennes 2005
    ident: ortho_historique_2005
    description: ''
    metadata_url: ''
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/jpeg&layers=ORTHOIMAGERY.ORTHOPHOTOS2005&styles=normal&tileMatrixSet=PM&tilePixelRatio=0&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
      provider: wms

  - title: Photographies aériennes 2004
    ident: ortho_historique_2004
    description: ''
    metadata_url: ''
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/jpeg&layers=ORTHOIMAGERY.ORTHOPHOTOS2004&styles=normal&tileMatrixSet=PM&tilePixelRatio=0&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
      provider: wms

  - title: Photographies aériennes 2003
    ident: ortho_historique_2003
    description: ''
    metadata_url: ''
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/jpeg&layers=ORTHOIMAGERY.ORTHOPHOTOS2003&styles=normal&tileMatrixSet=PM&tilePixelRatio=0&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
      provider: wms

  - title: Photographies aériennes 2002
    ident: ortho_historique_2002
    description: ''
    metadata_url: ''
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/jpeg&layers=ORTHOIMAGERY.ORTHOPHOTOS2002&styles=normal&tileMatrixSet=PM&tilePixelRatio=0&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
      provider: wms

  - title: Photographies aériennes 2001
    ident: ortho_historique_2001
    description: ''
    metadata_url: ''
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/jpeg&layers=ORTHOIMAGERY.ORTHOPHOTOS2001&styles=normal&tileMatrixSet=PM&tilePixelRatio=0&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
      provider: wms
  
  - title: Photographies aériennes 2000
    ident: ortho_historique_2000
    description: ''
    metadata_url: ''
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/jpeg&layers=ORTHOIMAGERY.ORTHOPHOTOS2000&styles=normal&tileMatrixSet=PM&tilePixelRatio=0&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
      provider: wms


  - title: Photographies aériennes 2011-2015
    ident: ortho_historique_20112015
    description: ''
    metadata_url: ''
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/jpeg&layers=ORTHOIMAGERY.ORTHOPHOTOS2011-2015&styles=normal&tileMatrixSet=PM&tilePixelRatio=0&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
      provider: wms

  - title: Photographies aériennes 2006-2010
    ident: ortho_historique_20062010
    description: ''
    metadata_url: ''
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/jpeg&layers=ORTHOIMAGERY.ORTHOPHOTOS2006-2010&styles=normal&tileMatrixSet=PM&tilePixelRatio=0&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
      provider: wms

  - title: Photographies aériennes 2000-2005
    ident: ortho_historique_20002005
    description: ''
    metadata_url: ''
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/jpeg&layers=ORTHOIMAGERY.ORTHOPHOTOS2000-2005&styles=normal&tileMatrixSet=PM&tilePixelRatio=0&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
      provider: wms

  - title: Photographies aériennes 1950-1965
    ident: ortho_historique_19501965
    description: ''
    metadata_url: ''
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/jpeg&layers=ORTHOIMAGERY.ORTHOPHOTOS.1950-1965&styles=normal&tileMatrixSet=PM&tilePixelRatio=0&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
      provider: wms