---
title: Agriculture
ident: ''
description: Couches liées à l'agriculture
metadata_url: ''
type: folder
children:

  - title: Registre Parcellaire Graphique (RPG) - Dernière édition
    ident: rpg_lastest
    description: >-
      BDD géographique servant de référence à l'instruction des aides de la politique agricole commune (PAC)
    metadata_url: https://artificialisation.developpement-durable.gouv.fr/bases-donnees/registre-parcellaire-graphique
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/png&layers=LANDUSE.AGRICULTURE.LATEST&styles=normal&tileMatrixSet=PM&tilePixelRatio=0&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
      provider: wms

  - title: Bandes tampons des cours d'eau BCAE 4
    ident: bcae_eau
    description: >-
      Cours d’eau concernés par les règles des Bonnes Conditions Agricoles et Environnementales (BCAE) de la PAC 
      et devant rester bordés d'une bande enherbée
    metadata_url: https://www.geoportail.gouv.fr/donnees/cours-eau-bcae-2021
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/png&layers=HYDROGRAPHY.BCAE.LATEST&styles=normal&tileMatrixSet=PM&tilePixelRatio=0&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
      provider: wms

  - title: Prairies sensibles BCAE 9
    ident: bcae_prairie
    description: >-
      Prairies permanentes désignées comme écologiquement sensibles au titre des règles des bonnes conditions 
      agricoles et environnementales (BCAE)
    metadata_url: https://www.geoportail.gouv.fr/donnees/prairies-sensibles-bcae
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/png&layers=PRAIRIES.SENSIBLES.BCAE&styles=normal&tileMatrixSet=PM&tilePixelRatio=0&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
      provider: wms

  - title: Parcelles AOC viticoles
    ident: aoc
    description: >-
      Délimitations parcellaires AOC viticoles diffusées par l'INAO
    metadata_url: https://www.geoportail.gouv.fr/donnees/inao-aoc-viticoles-parcellaire
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/png&layers=Aire-Parcellaire&styles=normal&tileMatrixSet=PM&tilePixelRatio=0&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
      provider: wms

  - title: Registre Parcellaire Graphique (RPG) 2021
    ident: rpg_2021
    description: >-
      BDD géographique servant de référence à l'instruction des aides de la politique agricole commune (PAC)
    metadata_url: https://artificialisation.developpement-durable.gouv.fr/bases-donnees/registre-parcellaire-graphique
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/png&layers=LANDUSE.AGRICULTURE2021&styles=normal&tileMatrixSet=PM&tilePixelRatio=0&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
      provider: wms

  - title: Registre Parcellaire Graphique (RPG) 2020
    ident: rpg_2020
    description: >-
      BDD géographique servant de référence à l'instruction des aides de la politique agricole commune (PAC)
    metadata_url: https://artificialisation.developpement-durable.gouv.fr/bases-donnees/registre-parcellaire-graphique
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/png&layers=LANDUSE.AGRICULTURE2020&styles=normal&tileMatrixSet=PM&tilePixelRatio=0&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
      provider: wms

  - title: Registre Parcellaire Graphique (RPG) 2019
    ident: rpg_2019
    description: >-
      BDD géographique servant de référence à l'instruction des aides de la politique agricole commune (PAC)
    metadata_url: https://artificialisation.developpement-durable.gouv.fr/bases-donnees/registre-parcellaire-graphique
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/png&layers=LANDUSE.AGRICULTURE2019&styles=normal&tileMatrixSet=PM&tilePixelRatio=0&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
      provider: wms

  - title: Registre Parcellaire Graphique (RPG) 2018
    ident: rpg_2018
    description: >-
      BDD géographique servant de référence à l'instruction des aides de la politique agricole commune (PAC)
    metadata_url: https://artificialisation.developpement-durable.gouv.fr/bases-donnees/registre-parcellaire-graphique
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/png&layers=LANDUSE.AGRICULTURE2018&styles=normal&tileMatrixSet=PM&tilePixelRatio=0&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
      provider: wms

  - title: Registre Parcellaire Graphique (RPG) 2017
    ident: rpg_2017
    description: >-
      BDD géographique servant de référence à l'instruction des aides de la politique agricole commune (PAC)
    metadata_url: https://artificialisation.developpement-durable.gouv.fr/bases-donnees/registre-parcellaire-graphique
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/png&layers=LANDUSE.AGRICULTURE2017&styles=normal&tileMatrixSet=PM&tilePixelRatio=0&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
      provider: wms

  - title: Registre Parcellaire Graphique (RPG) 2016
    ident: rpg_2016
    description: >-
      BDD géographique servant de référence à l'instruction des aides de la politique agricole commune (PAC)
    metadata_url: https://artificialisation.developpement-durable.gouv.fr/bases-donnees/registre-parcellaire-graphique
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/png&layers=LANDUSE.AGRICULTURE2016&styles=normal&tileMatrixSet=PM&tilePixelRatio=0&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
      provider: wms

  - title: Registre Parcellaire Graphique (RPG) 2015
    ident: rpg_2015
    description: >-
      BDD géographique servant de référence à l'instruction des aides de la politique agricole commune (PAC)
    metadata_url: https://artificialisation.developpement-durable.gouv.fr/bases-donnees/registre-parcellaire-graphique
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/png&layers=LANDUSE.AGRICULTURE2015&styles=normal&tileMatrixSet=PM&tilePixelRatio=0&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
      provider: wms

  - title: Registre Parcellaire Graphique (RPG) 2014
    ident: rpg_2014
    description: >-
      BDD géographique servant de référence à l'instruction des aides de la politique agricole commune (PAC)
    metadata_url: https://artificialisation.developpement-durable.gouv.fr/bases-donnees/registre-parcellaire-graphique
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/png&layers=LANDUSE.AGRICULTURE2014&styles=normal&tileMatrixSet=PM&tilePixelRatio=0&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
      provider: wms

  - title: Registre Parcellaire Graphique (RPG) 2013
    ident: rpg_2013
    description: >-
      BDD géographique servant de référence à l'instruction des aides de la politique agricole commune (PAC)
    metadata_url: https://artificialisation.developpement-durable.gouv.fr/bases-donnees/registre-parcellaire-graphique
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/png&layers=LANDUSE.AGRICULTURE2013&styles=normal&tileMatrixSet=PM&tilePixelRatio=0&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
      provider: wms

  - title: Registre Parcellaire Graphique (RPG) 2012
    ident: rpg_2012
    description: >-
      BDD géographique servant de référence à l'instruction des aides de la politique agricole commune (PAC)
    metadata_url: https://artificialisation.developpement-durable.gouv.fr/bases-donnees/registre-parcellaire-graphique
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/png&layers=LANDUSE.AGRICULTURE2012&styles=normal&tileMatrixSet=PM&tilePixelRatio=0&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
      provider: wms

  - title: Registre Parcellaire Graphique (RPG) 2011
    ident: rpg_2011
    description: >-
      BDD géographique servant de référence à l'instruction des aides de la politique agricole commune (PAC)
    metadata_url: https://artificialisation.developpement-durable.gouv.fr/bases-donnees/registre-parcellaire-graphique
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/png&layers=LANDUSE.AGRICULTURE2011&styles=normal&tileMatrixSet=PM&tilePixelRatio=0&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
      provider: wms

  - title: Registre Parcellaire Graphique (RPG) 2010
    ident: rpg_2010
    description: >-
      BDD géographique servant de référence à l'instruction des aides de la politique agricole commune (PAC)
    metadata_url: https://artificialisation.developpement-durable.gouv.fr/bases-donnees/registre-parcellaire-graphique
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/png&layers=LANDUSE.AGRICULTURE2010&styles=normal&tileMatrixSet=PM&tilePixelRatio=0&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
      provider: wms

  - title: Registre Parcellaire Graphique (RPG) 2009
    ident: rpg_2009
    description: >-
      BDD géographique servant de référence à l'instruction des aides de la politique agricole commune (PAC)
    metadata_url: https://artificialisation.developpement-durable.gouv.fr/bases-donnees/registre-parcellaire-graphique
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/png&layers=LANDUSE.AGRICULTURE2009&styles=normal&tileMatrixSet=PM&tilePixelRatio=0&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
      provider: wms

  - title: Registre Parcellaire Graphique (RPG) 2008
    ident: rpg_2008
    description: >-
      BDD géographique servant de référence à l'instruction des aides de la politique agricole commune (PAC)
    metadata_url: https://artificialisation.developpement-durable.gouv.fr/bases-donnees/registre-parcellaire-graphique
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/png&layers=LANDUSE.AGRICULTURE2008&styles=normal&tileMatrixSet=PM&tilePixelRatio=0&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
      provider: wms

  - title: Registre Parcellaire Graphique (RPG) 2007
    ident: rpg_2007
    description: >-
      BDD géographique servant de référence à l'instruction des aides de la politique agricole commune (PAC)
    metadata_url: https://artificialisation.developpement-durable.gouv.fr/bases-donnees/registre-parcellaire-graphique
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/png&layers=LANDUSE.AGRICULTURE2007&styles=normal&tileMatrixSet=PM&tilePixelRatio=0&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
      provider: wms