---
title: Occupation du sol
ident: ''
description: Données d'occupation du sol (IGN)
metadata_url: ''
type: folder
children:

  - title: OCS GE - Couverture du sol
    ident: ocsge_couverture
    description: >-
      L'OCcupation du Sol à Grande Echelle (OCS GE) est une base de données vectorielle produite par l'IGN pour la description de l’occupation du sol. Elle s’appuie sur un modèle ouvert séparant la couverture du sol et l’usage du sol
    metadata_url: https://artificialisation.developpement-durable.gouv.fr/bases-donnees/ocs-ge
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/png&layers=OCSGE.COUVERTURE&styles=normal&tileMatrixSet=PM&tilePixelRatio=0&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
      provider: wms
  
  - title: OCS GE - Usage du sol
    ident: ocsge_usage
    description: >-
      L'OCcupation du Sol à Grande Echelle (OCS GE) est une base de données vectorielle produite par l'IGN pour la description de l’occupation du sol. Elle s’appuie sur un modèle ouvert séparant la couverture du sol et l’usage du sol
    metadata_url: https://artificialisation.developpement-durable.gouv.fr/bases-donnees/ocs-ge
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/png&layers=OCSGE.USAGE&styles=normal&tileMatrixSet=PM&tilePixelRatio=0&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
      provider: wms
  
  - title: Corine Land Cover 2018
    ident: clc
    description: >-
      Inventaire biophysique européen de l’occupation des sols à l'échelle 1:100000. CLC permet de cartographier des unités homogènes d’occupation des sols d’une surface minimale de 25 ha
    metadata_url: https://www.statistiques.developpement-durable.gouv.fr/corine-land-cover-0
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/png&layers=LANDCOVER.CLC18_FR&styles=CORINE Land Cover - France métropolitaine&tileMatrixSet=PM&tilePixelRatio=0&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
      provider: wms