---
title: Altimétrie (IGN)
ident: ''
description: Données MNT, MNS, pente, altitude, estompage, trait de côte, masque de source
metadata_url: https://geoservices.ign.fr/services-web-experts-altimetrie
type: folder
children:

  - title: Altitude - Carte du relief
    ident: relief
    description: >-
      Représentation de l’altitude sous forme de teintes hypsométriques (fausses couleurs)
    metadata_url: https://www.geoportail.gouv.fr/donnees/carte-du-relief
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/jpeg&layers=ELEVATION.SLOPES&styles=normal&tileMatrixSet=PM&tilePixelRatio=0&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
      provider: wms

  - title: Carte des pentes
    ident: pentes
    description: >-
      Représentation des classes de pentes supérieures à 30°, 35°, 40°, et 45° obtenues par traitement 
      du MNT RGE ALTI au pas de 1m
    metadata_url: https://www.geoportail.gouv.fr/donnees/carte-des-pentes
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/png&layers=GEOGRAPHICALGRIDSYSTEMS.SLOPES.MOUNTAIN&styles=normal&tileMatrixSet=PM&tilePixelRatio=0&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
      provider: wms

  - title: Courbes de niveau
    ident: courbes_niveau
    description: >-
      Modèle numérique de terrain sous forme de courbes de même altitude, appelées aussi « isoplèthes d’altitude »
    metadata_url: https://geoservices.ign.fr/documentation/donnees/alti/courbes-de-niveau
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/png&layers=ELEVATION.CONTOUR.LINE&styles=normal&tileMatrixSet=PM&tilePixelRatio=0&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
      provider: wms