---
title: Géorisques
ident: 
description: >-
  Couches diffusées sur le portail Géorisques par le Bureau des Recherches Géologiques et Minières (BRGM) 
  et le Ministère de la Transition Ecologique.
type: folder
children:

  - title: CASIAS - Base des Anciens Sites Industriels et Activités de Service (Point)
    ident: casias
    description: >-
      La CASIAS anciennement BASIAS recense les sites industriels, abandonnés ou en activité, 
      susceptibles d'engendrer une pollution de l'environnement
    metadata_url: https://www.georisques.gouv.fr/articles-risques/pollutions-sols-sis-anciens-sites-industriels/basias
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/png&layers=SSP_ETS_GE_POINT&styles&tilePixelRatio=0&url=http://georisques.gouv.fr/services
      provider: wms

  - title: CASIAS - Base des Anciens Sites Industriels et Activités de Service (Polygon)
    ident: casias
    description: >-
      La CASIAS anciennement BASIAS recense les sites industriels, abandonnés ou en activité, 
      susceptibles d'engendrer une pollution de l'environnement
    metadata_url: https://www.georisques.gouv.fr/articles-risques/pollutions-sols-sis-anciens-sites-industriels/basias
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/png&layers=SSP_ETS_GE_POLYGON&styles&tilePixelRatio=0&url=http://georisques.gouv.fr/services
      provider: wms

  - title: Sites et Sols Pollués ou potentiellement pollués (SSP, ex-BASOL)
    ident: basol
    description: >-
      Sites et sols pollués (ou potentiellement pollués) appelant une action des pouvoirs publics, 
      à titre préventif ou curatif
    metadata_url: https://www.georisques.gouv.fr/articles-risques/pollutions-sols-sis-anciens-sites-industriels/basol
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:2154&dpiMode=7&format=image/png&layers=SSP_INSTRUCTION&styles&url=https://www.georisques.gouv.fr/services
      provider: wms

  - title: Plan de Prévention des Risques d'inondation (PPRi)
    ident: ppri
    description: >-
      Le plan de prévention des risques naturels d'inondation (PPRi ou PPRNi) 
      Le PPRNi est un outil de prévention majeur contre les risques naturels d'inondation, 
      permettant d'influer sur l'occupation et l'utilisation des sols
    metadata_url: https://www.georisques.gouv.fr/plans-de-prevention-des-risques-naturels
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:2154&featureCount=10&format=image/png&layers=PPRN_ZONE_INOND_FXX&maxHeight=256&maxWidth=256&styles=default&url=https://www.georisques.gouv.fr/services
      provider: wms

  - title: Surface inondable - Aléa submersion rare ou millénial
    ident: alea_submersion_rare
    description: >-
      Les inondations et les submersions marines sont les risques naturels qui
      concernent le plus grand nombre de personnes en France. Phénomène
      saisonnier qui trouve sa source dans des précipitations soutenues et
      durables, l’inondation peut aussi venir de la mer ou des eaux
      souterraines. Ce risque naturel peut être fortement accentué par les
      activités humaines et les aménagements
    metadata_url: https://www.georisques.gouv.fr/donnees/bases-de-donnees/zonages-inondation-rapportage-2020
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/png&layers=ISO_HT_03_04FAI_MYT&styles&tilePixelRatio=0&url=http://georisques.gouv.fr/services
      provider: wms

  - title: Surface inondable - Aléa submersion moyen ou centennal
    ident: alea_submersion_moyen
    description: >-
      Les inondations et les submersions marines sont les risques naturels qui
      concernent le plus grand nombre de personnes en France. Phénomène
      saisonnier qui trouve sa source dans des précipitations soutenues et
      durables, l’inondation peut aussi venir de la mer ou des eaux
      souterraines. Ce risque naturel peut être fortement accentué par les
      activités humaines et les aménagements
    metadata_url: https://www.georisques.gouv.fr/donnees/bases-de-donnees/zonages-inondation-rapportage-2020
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/png&layers=ISO_HT_03_03MCC_FXX&styles&tilePixelRatio=0&url=http://georisques.gouv.fr/services
      provider: wms

  - title: Surface inondable - Aléa débordement de cours d'eau fréquent ou décennal
    ident: alea_submersion_frequent
    description: >-
      Les inondations et les submersions marines sont les risques naturels qui
      concernent le plus grand nombre de personnes en France. Phénomène
      saisonnier qui trouve sa source dans des précipitations soutenues et
      durables, l’inondation peut aussi venir de la mer ou des eaux
      souterraines. Ce risque naturel peut être fortement accentué par les
      activités humaines et les aménagements
    metadata_url: https://www.georisques.gouv.fr/donnees/bases-de-donnees/zonages-inondation-rapportage-2020
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/png&layers=ISO_HT_03_01FOR_FXX&styles&tilePixelRatio=0&url=http://georisques.gouv.fr/services
      provider: wms

  - title: Canalisations de transport de matières dangereuses; Produits chimiques
    ident: canalisation_produit_chimique
    description: >-
      Il s’agit d’une canalisation qui achemine des produits chimiques vers des
      réseaux de distribution, d’autres ouvrages de transport, des entreprises
      industrielles ou commerciales, des sites de stockage ou de chargement.
      Cette dénomination ne s’applique pas au réseau de distribution de gaz en
      ville, mais aux conduites de transport longue distance, qui sont plus
      grosses (entre 8 et 120 cm de diamètre) et fonctionnent à des pressions
      plus importantes (jusqu’à 94 bars)
    metadata_url: https://www.georisques.gouv.fr/cartes-interactives#/
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/png&layers=C_PRODUITS_CHIM&styles&tilePixelRatio=0&url=http://georisques.gouv.fr/services
      provider: wms

  - title: Canalisations de transport de matières dangereuses; Gaz
    ident: canalisation_gaz
    description: >-
      Il s’agit d’une canalisation qui achemine du gaz vers des réseaux de
      distribution, d’autres ouvrages de transport, des entreprises industrielles
      ou commerciales, des sites de stockage ou de chargement. Cette dénomination
      ne s’applique pas au réseau de distribution de gaz en ville, mais aux
      conduites de transport longue distance, qui sont plus grosses (entre 8 et
      120 cm de diamètre) et fonctionnent à des pressions plus importantes
      (jusqu’à 94 bars)
    metadata_url: https://www.georisques.gouv.fr/cartes-interactives#/
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/png&layers=C_GAZ&styles&tilePixelRatio=0&url=http://georisques.gouv.fr/services
      provider: wms

  - title: Canalisations de transport de matières dangereuses; Hydrocarbure
    ident: canalisation_hydrocarbure
    description: >-
      Il s’agit d’une canalisation qui achemine des hydrocarbures vers des
      réseaux de distribution, d’autres ouvrages de transport, des entreprises
      industrielles ou commerciales, des sites de stockage ou de chargement.
      Cette dénomination ne s’applique pas au réseau de distribution de gaz en
      ville, mais aux conduites de transport longue distance, qui sont plus
      grosses (entre 8 et 120 cm de diamètre) et fonctionnent à des pressions
        metadata_url: https://www.georisques.gouv.fr/cartes-interactives#/
    metadata_url: https://www.georisques.gouv.fr/cartes-interactives#/
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/png&layers=C_HYDROCARBURES&styles&tilePixelRatio=0&url=http://georisques.gouv.fr/services
      provider: wms
     
  - title: Exposition au retrait-gonflement des argiles
    ident: argiles
    description: >-
      Les terrains argileux superficiels peuvent voir leur volume varier à la suite d'une modification de 
      leur teneur en eau, en lien avec les conditions météorologiques.
      Ils se « rétractent » lors des périodes de sécheresse (phénomène de « retrait ») 
      et gonflent au retour des pluies lorsqu’ils sont de nouveau hydratés (phénomène de « gonflement »).
      Ces variations sont lentes, mais elles peuvent atteindre une amplitude 
      assez importante pour endommager les bâtiments localisés sur ces terrains.
      Le phénomène de retrait-gonflement des argiles engendre chaque année des dégâts considérables, 
      indemnisables au titre des catastrophes naturelles. 
      La grande majorité des sinistres concerne les maisons individuelles
    metadata_url: https://www.georisques.gouv.fr/cartes-interactives#/
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/png&layers=C_HYDROCARBURES&styles&tilePixelRatio=0&url=http://georisques.gouv.fr/services
      provider: wms