---
title: Foncier
ident: ''
description: Couches relatives au foncier (IGN)
type: folder
children:

  - title: PCI - Plan Cadastral Informatisé Vecteur
    ident: pci
    description: >-
      Le plan cadastral est un assemblage d’environ 600 000 feuilles ou planches représentant chacune 
      une section ou une partie d’une section cadastrale
    metadata_url: https://geoservices.ign.fr/parcellaire-express-pci
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&fdpiMode=7&format=image/png&http-header:referer=&layers=CADASTRALPARCELS.PARCELLAIRE_EXPRESS&styles=PCI vecteur&tileMatrixSet=PM&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
      provider: wms

  - title: Decalage de la representation cadastrale
    ident: decalage_cadastre
    description: >-
      Cartographie des décalages entre les données BD Parcellaire et Parcellaire Express
    metadata_url: https://www.datagrandest.fr/portail/fr/actualites/evolution-du-produit-parcellaire-lign
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&fdpiMode=7&format=image/png&http-header:referer=&layers=CADASTRALPARCELS.HEATMAP&styles=DECALAGE DE LA REPRESENTATION CADASTRALE&tileMatrixSet=PM&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
      provider: wms

  - title: Qualité du géoréférencement de la BD Parcellaire
    ident: qualite_bd_parcellaire
    description: >-
      Qualité du géoréférencement de la BD Parcellaire
    metadata_url: https://geoservices.ign.fr/sites/default/files/2021-07/DL_BDPARCELLAIRE_1-2.pdf
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&fdpiMode=7&format=image/png&http-header:referer=&layers=CADASTRALPARCELS.QUALREFBDP&styles=DIVCAD_MTD&tileMatrixSet=PM&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
      provider: wms