---
title: Urbanisme et patrimoine
ident: ''
description: >-
  Couches diffusées par le Géoportail de l'Urbanisme, l'IGN et l'atlas du patrimoine
type: folder
children:

  - title: Monuments historiques
    ident: monuments_historiques
    description: >-
      Un monument historique est un immeuble (bâti ou non bâti : parc,
      jardin, grotte…) ou un objet mobilier (meuble ou immeuble par destination) recevant
      un statut juridique particulier destiné à le protéger pour son intérêt historique,
      artistique, architectural mais aussi technique ou scientifique afin qu’il soit
      conservé, restauré et mis en valeur
    metadata_url: https://www.geoportail-urbanisme.gouv.fr/services/
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:2154&dpiMode=7&format=image/png&layers=monument_historique&styles&tilePixelRatio=0&url=https://wxs-gpu.mongeoportail.ign.fr/externe/vkd1evhid6jdj5h4hkhyzjto/wms/v
      provider: wms

  - title: Monuments nationaux
    ident: monuments_nationaux
    description: ''
    metadata_url: ''
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/png&layers=POI.MONUMENTS_BDD_WLD_WM&styles&tilePixelRatio=0&url=https://wxs-gpu.mongeoportail.ign.fr/externe/vkd1evhid6jdj5h4hkhyzjto/wms/v
      provider: wms

  - title: Monuments naturels et sites
    ident: Monuments_naturels_sites
    description: >-
      Un site inscrit est un espace naturel ou bâti de caractère artistique,
      historique, scientifique, légendaire ou pittoresque qui nécessite d’être conservé
    metadata_url: https://www.culture.gouv.fr/Regions/Drac-Centre-Val-de-Loire/Nos-secteurs-d-activite/Espaces-proteges/Les-sites-inscrits-et-classes
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:2154&dpiMode=7&format=image/png&layers=monument_naturel_site&styles&tilePixelRatio=0&url=https://wxs-gpu.mongeoportail.ign.fr/externe/vkd1evhid6jdj5h4hkhyzjto/wms/v
      provider: wms

  - title: Emprise des documents d'urbanisme (petite échelle)
    ident: emprise_documents_urbanisme
    description: >-
      Emprise des documents d'urbanisme (petite échelle)
    metadata_url: https://www.geoportail-urbanisme.gouv.fr/services/
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:4326&dpiMode=7&format=image/png&layers=document&styles&url=https://wxs-gpu.mongeoportail.ign.fr/externe/vkd1evhid6jdj5h4hkhyzjto/wms/v
      provider: wms

  - title: PLU - Documents d'urbanisme
    ident: plu
    description: >-
      PLU, POS, CC : Le plan local d''urbanisme (PLU) -anciennement plan
      d''occupation des sols (POS)- fixe les règles générales et les servitudes d''utilisation
      du sol sur la totalité du territoire communal
    metadata_url: https://www.geoportail-urbanisme.gouv.fr/services/
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:4326&dpiMode=7&format=image/png&layers=du&styles&url=https://wxs-gpu.mongeoportail.ign.fr/externe/vkd1evhid6jdj5h4hkhyzjto/wms/v
      provider: wms

  - title: SCOT - Schéma de Cohérence Territoriale
    ident: scot
    description: >-
      Le schéma de cohérence territoriale (SCoT) est un document d'urbanisme
      qui, à l'échelle d'un territoire de projet ou bassin de vie (périmètre intercommunal
      ou au-delà), détermine l'organisation spatiale et les grandes orientations de
      développement d'un territoire.
    metadata_url: https://www.geoportail-urbanisme.gouv.fr/services/
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:4326&dpiMode=7&format=image/png&layers=scot&styles&url=https://wxs-gpu.mongeoportail.ign.fr/externe/vkd1evhid6jdj5h4hkhyzjto/wms/v
      provider: wms

  - title: Communes loi littoral
    ident: communes_loi_littoral
    description: >-
      La loi Littoral concerne plus de 1 200 communes riveraines de la mer,
      mais aussi de grands lacs, d'estuaires ou de deltas. Face à la pression urbaine,
      aux phénomènes d'érosion ou de submersion marine subis par ces territoires, elle
      tente de concilier préservation et développement du littoral
    metadata_url: https://carmen.naturefrance.fr/
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:4326&featureCount=10&format=image/png&layers=Loi_littoral_2020&maxHeight=256&maxWidth=256&styles=default&url=http://ws.carmen.developpement-durable.gouv.fr/WMS/91/loi_littoral?
      provider: wms

  - title: Prescriptions
    ident: prescriptions
    description: ''
    metadata_url: https://www.service-public.fr/particuliers/vosdroits/F642
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:4326&dpiMode=7&format=image/png&layers=prescription&styles&url=https://wxs-gpu.mongeoportail.ign.fr/externe/vkd1evhid6jdj5h4hkhyzjto/wms/v
      provider: wms

  - title: Prescriptions des PSMV
    ident: prescriptions_psmv
    description: >-
      Le PSMV est un document de planification prévu pour assurer la sauvegarde
      et la mise en valeur des sites patrimoniaux remarquables (et, avant eux, des secteurs
      sauvegardés)
    metadata_url: https://www.service-public.fr/particuliers/vosdroits/F642
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:4326&dpiMode=7&format=image/png&layers=prescription_psmv&styles&url=https://wxs-gpu.mongeoportail.ign.fr/externe/vkd1evhid6jdj5h4hkhyzjto/wms/v
      provider: wms

  - title: Aéroports
    ident: aeroports
    description: ''
    metadata_url: ''
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&fdpiMode=7&format=image/png&http-header:referer=&layers=TRANSPORTNETWORKS.RUNWAYS&styles=normal&tileMatrixSet=PM&url=https://wxs.ign.fr/topographie/geoportail/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
      provider: wms

  - title: Communes 2019 soumises à la loi Montagne de 1985
    ident: communes_loi_montagne
    description: >-
      Missionné par la DHUP (Bureau de la législation de l'urbanisme), le
      Cerema a réalisé une actualisation au 1er janvier 2019 de la liste des communes
      concernées par l'application des dispositions d'urbanisme de la loi Montagne (Loi
      n° 85-30 du 9 janvier 1985 relative au développement et à la protection de la
      montagne, Loi n° 2016-1888 du 28 décembre 2016 de modernisation, de développement
      et de protection des territoires de montagne).
    metadata_url: https://catalogue.datara.gouv.fr/geonetwork/srv/fre/catalog.search#/metadata/17aaef31-af53-4d68-97c8-741e695f1820
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:2154&featureCount=10&format=image/png&layers=layer31&maxHeight=256&maxWidth=256&styles=&url=https://datacarto.datara.gouv.fr/map/carte_zonage_amenagement?VERSION%3D1.3.0
      provider: wms