---
title: Eau
ident: ''
description: >-
  Données relatives aux services d'administration nationale des données et référentiels sur l'eau (SANDRE) et de Cart'eaux
metadata_url: ''
type: folder
children:

  - title: Segments de classement de continuité écologique - liste 1
    ident: continuite_eco_liste1
    description: >-
      Un Classement de Continuité Ecologique correspond à tout ou partie d'un cours ou d'un canal identifié. 
      Le classement en liste 1 a pour vocation de protéger certains cours d’eau des dégradations et permet 
      d’afficher un objectif de préservation à long terme
    metadata_url: https://geo.data.gouv.fr/fr/datasets/bbc59e0deb382a4e97e4bf75d08657fef8730552
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/png&layers=SegClassContinuiteEcoListe1&styles&url=https://services.sandre.eaufrance.fr/geo/sandre
      provider: wms


  - title: Segments de classement de continuité écologique - liste 2
    ident: continuite_eco_liste2
    description: >-
      Un Classement de Continuité Ecologique correspond à tout ou partie d'un cours ou d'un canal identifié. 
      La liste 2 annule, replace et complète la notion de « rivières classées », elle permet d’assurer rapidement 
      la compatibilité des ouvrages existants avec les objectifs de continuité écologique
    metadata_url: https://geo.data.gouv.fr/fr/datasets/bbc59e0deb382a4e97e4bf75d08657fef8730552
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/png&layers=SegClassContinuiteEcoListe2&styles&url=https://services.sandre.eaufrance.fr/geo/sandre
      provider: wms

  - title: Segments de classement de continuité écologique - liste 1/2
    ident: continuite_eco_liste_1_2
    description: >-
      Combinaison des listes de continuités écologiques 1 et 2
    metadata_url: https://geo.data.gouv.fr/fr/datasets/bbc59e0deb382a4e97e4bf75d08657fef8730552
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:3857&dpiMode=7&format=image/png&layers=SegClassContinuiteEco&styles&url=https://services.sandre.eaufrance.fr/geo/sandre
      provider: wms

  - title: Cours d'eau - BD Carthage
    ident: Cours d'eau - BD Carthage
    description: >-
      Entité hydrographique, une entité hydrographique est un cours d’eau naturel ou aménagé, 
      un bras naturel ou aménagé, une voie d’eau artificielle (canal,…), un plan d'eau ou une ligne littorale
    metadata_url: https://geo.data.gouv.fr/fr/datasets/ee5c709c9b7ff928ab2529b79ce6e879c4de6950
    type: wms_wmts_universal_layer
    params:
      uri: crs=EPSG:4326&dpiMode=7&format=image/png&layers=CoursEau&styles&url=https://services.sandre.eaufrance.fr/geo/sandre
      provider: wms
