---
title: BDTOPO (IGN)
ident: ''
description: >-
  La modélisation 2D du territoire et de ses infrastructures sur l'ensemble du territoire français produit par l'IGN
metadata_url: https://geoservices.ign.fr/bdtopo
type: folder
children:

  - title: Administatif
    ident: ''
    description: ''
    type: folder
    children: []

  - title: Bati
    ident: ''
    description: ''
    type: folder
    children:

    - title: Bâtiments
      ident: batiments
      description: >-
        Construction au-dessus du sol qui est utilisée pour abriter des humains,
        des animaux, des objets, pour la production de biens économiques ou pour la
        prestation de services et qui se réfère à toute structure construite ou érigée
        de façon permanente sur son site.
      metadata_url: https://geoservices.ign.fr/sites/default/files/2021-07/DC_BDTOPO_3-0.pdf#%5B%7B%22num%22%3A2238%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C29%2C382%2C0%5D
      type: wms_wmts_universal_layer
      params:
        uri: crs=EPSG:3857&fdpiMode=7&format=image/png&http-header:referer=&layers=BUILDINGS.BUILDINGS&styles=normal&tileMatrixSet=PM&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
        provider: wms

  - title: Occupation du sol
    ident: ''
    description: ''
    type: folder
    children:

    - title: Haies lineraires
      ident: haies
      description: >-
        La BD Haie est le résultat des travaux initiés dans le cadre du dispositif de suivi des bocages (DSB).
      metadata_url: https://geoservices.ign.fr/bdhaie
      type: wms_wmts_universal_layer
      params:
        uri: crs=EPSG:3857&fdpiMode=7&format=image/png&http-header:referer=&layers=hedge.hedge&styles=normal&tileMatrixSet=PM&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
        provider: wms

  - title: Transports
    ident: ''
    description: ''
    type: folder
    children:

    - title: Réseau ferroviaire
      ident: reseau_ferroviaire
      description: >-
        Portion de voie ferrée homogène
      metadata_url: https://geoservices.ign.fr/sites/default/files/2022-11/BDTOPO%C2%AE_Th%C3%A8me_Transport-Descriptif_de_contenu.pdf
      type: wms_wmts_universal_layer
      params:
        uri: crs=EPSG:3857&fdpiMode=7&format=image/png&http-header:referer=&layers=TRANSPORTNETWORKS.RAILWAYS&styles=normal&tileMatrixSet=PM&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
        provider: wms

    - title: Routes
      ident: routes
      description: >-
        Portion de voie de communication destinée aux automobiles, aux piétons, aux cycles ou aux animaux,homogène
      metadata_url: https://geoservices.ign.fr/sites/default/files/2023-10/DC_BDTOPO_Transport.pdf
      type: wms_wmts_universal_layer
      params:
        uri: crs=EPSG:3857&fdpiMode=7&format=image/png&http-header:referer=&layers=TRANSPORTNETWORKS.ROADS&styles=normal&tileMatrixSet=PM&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
        provider: wms

    - title: DGAC - PEB (Plans d'exposition aux bruits)
      ident: dgac_peb
      description: ''
      metadata_url: https://geoservices.ign.fr/sites/default/files/2023-10/DC_BDTOPO_Transport.pdf
      type: wms_wmts_universal_layer
      params:
        uri: crs=EPSG:3857&featureCount=10&format=image/png&layers=DGAC-PEB_BDD_FXX_WM_WMS&maxHeight=256&maxWidth=256&styles=&url=https://wxs.ign.fr/transports/geoportail/v/wms?VERSION%3D1.3.0
        provider: wms

    - title: DGAC - PGS (Plans de gêne sonore)
      ident: dgac_pgs
      description: ''
      metadata_url: https://geoservices.ign.fr/sites/default/files/2023-10/DC_BDTOPO_Transport.pdf
      type: wms_wmts_universal_layer
      params:
        uri: crs=EPSG:3857&featureCount=10&format=image/png&layers=DGAC-PGS_BDD_FXX_WM_WMS&maxHeight=256&maxWidth=256&styles=&url=https://wxs.ign.fr/transports/geoportail/v/wms?VERSION%3D1.3.0
        provider: wms

    - title: DGAC - PSA (Plans de servitudes aéronautiques)
      ident: dgac_psa
      description: ''
      metadata_url: https://geoservices.ign.fr/sites/default/files/2023-10/DC_BDTOPO_Transport.pdf
      type: wms_wmts_universal_layer
      params:
        uri: crs=EPSG:3857&featureCount=10&format=image/png&layers=TRANSPORTS.AIRNOISE&maxHeight=256&maxWidth=256&styles=&url=https://wxs.ign.fr/transports/geoportail/v/wms?VERSION%3D1.3.0
        provider: wms

    - title: DGAC Documentations - PEB (Plans d'exposition aux bruits)
      ident: dgac_documentations_peb
      description: ''
      metadata_url: https://geoservices.ign.fr/sites/default/files/2023-10/DC_BDTOPO_Transport.pdf
      type: wms_wmts_universal_layer
      params:
        uri: crs=EPSG:3857&featureCount=10&format=image/png&layers=DGAC-PEB-POI_BDD_WLD_WM&maxHeight=256&maxWidth=256&styles=&url=https://wxs.ign.fr/transports/geoportail/v/wms?VERSION%3D1.3.0
        provider: wms

    - title: DGAC Documentations - PGS (Plans de gêne sonore)
      ident: dgac_documentations_pgs
      description: ''
      metadata_url: https://geoservices.ign.fr/sites/default/files/2023-10/DC_BDTOPO_Transport.pdf
      type: wms_wmts_universal_layer
      params:
        uri: crs=EPSG:3857&featureCount=10&format=image/png&layers=DGAC-PGS-POI_BDD_FXX_WM_WM&maxHeight=256&maxWidth=256&styles=&url=https://wxs.ign.fr/transports/geoportail/v/wms?VERSION%3D1.3.0
        provider: wms

    - title: DGAC Documentations - PSA (Plans de servitudes aéronautiques)
      ident: dgac_documentations_psa
      description: ''
      metadata_url: https://geoservices.ign.fr/sites/default/files/2023-10/DC_BDTOPO_Transport.pdf
      type: wms_wmts_universal_layer
      params:
        uri: crs=EPSG:3857&featureCount=10&format=image/png&layers=TRANSPORTS.AIRNOISE.DOCS&maxHeight=256&maxWidth=256&styles=&url=https://wxs.ign.fr/transports/geoportail/v/wms?VERSION%3D1.3.0
        provider: wms

  - title: Lieu nommés
    ident: ''
    description: ''
    type: folder
    children:

    - title: Dénominations géographiques
      ident: Denominations_geographiques
      description: >-
        Dénominations topologiques sur le territoire
      metadata_url: ''
      type: wms_wmts_universal_layer
      params:
        uri: crs=EPSG:3857&fdpiMode=7&format=image/png&http-header:referer=&layers=GEOGRAPHICALNAMES.NAMES&styles=normal&tileMatrixSet=PM&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
        provider: wms

  - title: Zones réglemenentées
    ident: ''
    description: ''
    type: folder
    children: []

  - title: Services et activités
    ident: ''
    description: ''
    type: folder
    children:

    - title: Lignes électriques aériennes haute tension
      ident: lignes_electriques
      description: >-
        Toutes les lignes électriques à haute (voltage ≥ 63 kV) ou à très
        haute tension (voltage ≥ 150 kV) sont incluses, sauf les souterraines.
      metadata_url: https://geoservices.ign.fr/sites/default/files/2021-07/DC_BDTOPO_3-0.pdf#%5B%7B%22num%22%3A5941%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C29%2C434%2C0%5D
      type: wms_wmts_universal_layer
      params:
        uri: crs=EPSG:3857&fdpiMode=7&format=image/png&http-header:referer=&layers=UTILITYANDGOVERNMENTALSERVICES.ALL&styles=normal&tileMatrixSet=PM&url=https://data.geopf.fr/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities
        provider: wms