---
title: Occitanie
ident: ''
description: >-
  Zonages environnementaux diffusés par la Direction Régionale de l'Environnement,
  de l'Aménagement et du Logement d'Occitanie (DREAL).
type: folder
children:
  
  - title: PNA
    ident: ''
    description: ''
    type: folder
    children:

    - title: PNA Aigle de Bonelli - Domaines vitaux
      ident: aigle_bonelli_vitaux
      description: >-
        L'aigle de Bonelli est une espèce protégée au niveau national et
        comme telle, en vertu de l'arrêté du 29 octobre 2009 fixant la liste des oiseaux
        protégés sur l’ensemble du territoire et les modalités de leur protection (article
        3)
      metadata_url: https://catalogue.picto-occitanie.fr/geonetwork/srv/fre/catalog.search#/metadata/5d6e6a05-094a-43f7-a881-b70a60a6df60
      type: wms_wmts_universal_layer
      params:
        uri: crs=EPSG:2154&featureCount=10&format=image/png&layers=r_pnaaigledebonelli_dv_s_000&maxHeight=256&maxWidth=256&styles=&url=https://datacarto.picto-occitanie.fr/wms
        provider: wms

    - title: PNA Aigle de Bonelli - Zones d’erratisme
      ident: aigle_bonelli_erratisme
      description: >-
        L'aigle de Bonelli est une espèce protégée au niveau national et
        comme telle, en vertu de l'arrêté du 29 octobre 2009 fixant la liste des oiseaux
        protégés sur l’ensemble du territoire et les modalités de leur protection (article
        3)
      metadata_url: https://catalogue.picto-occitanie.fr/geonetwork/srv/fre/catalog.search#/metadata/8b070f45-92e3-4840-a11d-fd7816f3072c
      type: wms_wmts_universal_layer
      params:
        uri: crs=EPSG:2154&featureCount=10&format=image/png&layers=r_pnaaigledebonelli_er_s_000&maxHeight=256&maxWidth=256&styles=&url=https://datacarto.picto-occitanie.fr/wms
        provider: wms

    - title: PNA Butoir Etoilé
      ident: butoir_etoile
      description: >-
        Le Butor étoilé est une espèce d'oiseaux échassiers de la famille
        des ardéidés. Considéré d'après les recensements effectués comme une espèce
        très menacée, sa population est en déclin rapide en Europe et aurait chuté de
        35 à 45 % en France en 30 ans.
      metadata_url: https://www.ecologie.gouv.fr/sites/default/files/PNA_Butor-etoile_2008-2012.pdf
      type: wms_wmts_universal_layer
      params:
        uri: crs=EPSG:2154&featureCount=10&format=image/png&layers=r_pnabutoiretoile_s_r76&maxHeight=256&maxWidth=256&styles=&url=https://datacarto.picto-occitanie.fr/wms
        provider: wms

    - title: PNA Chiroptère
      ident: chiroptère
      description: >-
        Les Chiroptères, appelés couramment chauves-souris ou chauvesouris
      metadata_url: https://www.ecologie.gouv.fr/sites/default/files/PNA_Chiropteres_2016-2025.pdf
      type: wms_wmts_universal_layer
      params:
        uri: crs=EPSG:2154&featureCount=10&format=image/png&layers=r_pnachiroptere_s_r76&maxHeight=256&maxWidth=256&styles=&url=https://datacarto.picto-occitanie.fr/wms
        provider: wms

    - title: PNA Desman des Pyrénées - Zone de présence en Occitanie
      ident: desman_pyrennees
      description: >-
        Le Desman des Pyrénées, également appelé Rat-trompette, est une espèce
        de petits mammifères de la famille des Talpidés, endémique de la chaîne des
        Pyrénées et des zones montagneuses du nord-ouest de la péninsule Ibérique.
      metadata_url: https://www.consultations-publiques.developpement-durable.gouv.fr/IMG/pdf/pna_desman.pdf
      type: wms_wmts_universal_layer
      params:
        uri: crs=EPSG:2154&featureCount=10&format=image/png&layers=r_pna_desmandespyrennes_s_r76ext&maxHeight=256&maxWidth=256&styles=&url=https://datacarto.picto-occitanie.fr/wms
        provider: wms

    - title: PNA Emyde lépreuse
      ident: emyde_lepreuse
      description: >-
        Mauremys leprosa, l'Émyde lépreuse, est une espèce de tortues dulçaquicoles
        de la famille des Geoemydidae. Cette espèce est classifiée 'Vulnérable' à l'échelle
        européenne par l'Union Internationale pour la Conservation de la Nature.
      metadata_url: https://www.ecologie.gouv.fr/sites/default/files/PNA_Emyde-lepreuse_2012-2016.pdf
      type: wms_wmts_universal_layer
      params:
        uri: crs=EPSG:2154&featureCount=10&format=image/png&layers=r_pnaemydelepreuse_s_r76&maxHeight=256&maxWidth=256&styles=&url=https://datacarto.picto-occitanie.fr/wms
        provider: wms

    - title: PNA Faucon Crecerellette DV
      ident: faucon_crecerellette
      description: >-
        Le Faucon crécerellette est une petite espèce de rapaces très semblable
        au Faucon crécerelle mais plus svelte. Il peut être désigné sous le nom vernaculaire
        de Crécerine.
      metadata_url: https://www.ecologie.gouv.fr/sites/default/files/PNA%20Faucon%20Crecerellette_2021-2030.pdf
      type: wms_wmts_universal_layer
      params:
        uri: crs=EPSG:2154&featureCount=10&format=image/png&layers=r_pnafauconcrecerellettedv_s_r76ext&maxHeight=256&maxWidth=256&styles=&url=https://datacarto.picto-occitanie.fr/wms
        provider: wms

    - title: PNA Grand tétras - Zone de présence globale (zone 1)
      ident: grand_tetras
      description: >- 
        Les Chiroptères, appelés couramment chauves-souris ou chauvesouris
      metadata_url: https://www.bourgogne-franche-comte.developpement-durable.gouv.fr/plan-national-d-actions-en-faveur-du-grand-tetras-a7661.html
      type: wms_wmts_universal_layer
      params:
        uri: crs=EPSG:2154&featureCount=10&format=image/png&layers=r_pnagrandtetras_zonedepresence_s_r76ext&maxHeight=256&maxWidth=256&styles=&url=https://datacarto.picto-occitanie.fr/wms
        provider: wms

    - title: PNA Gypaète
      ident: gypaete
      description: >-
        Le Gypaète barbu (Gypaetus barbatus) est un grand rapace nécrophage qui présente une envergure imposante
      metadata_url: https://www.ecologie.gouv.fr/sites/default/files/PNA_Gypaete-barbu_2010-2020.pdf
      type: wms_wmts_universal_layer
      params:
        uri: crs=EPSG:2154&featureCount=10&format=image/png&layers=r_pnagypaete_s_r76ext&maxHeight=256&maxWidth=256&styles=&url=https://datacarto.picto-occitanie.fr/wms
        provider: wms

    - title: PNA Lézard des Pyrénées - Zones de présences dans les Pyrénées
      ident: lezard_pyrenees
      description: >-
        Le Lézard des Pyrénées, ou Lézard de Bonnal, est une espèce de sauriens de la famille des Lacertidae
      metadata_url: https://www.ecologie.gouv.fr/sites/default/files/PNA_Lezards-des-Pyrenees_2013-2017_.pdf
      type: wms_wmts_universal_layer
      params:
        uri: crs=EPSG:2154&featureCount=10&format=image/png&layers=r_pnalezardpyreneeszonedepresence_s_r76&maxHeight=256&maxWidth=256&styles=&url=https://datacarto.picto-occitanie.fr/wms
        provider: wms

    - title: PNA Lézard Ocellé
      ident: lezard_ocelle
      description: >-
        Le Lézard ocellé est une espèce de sauriens de la famille des Lacertidae.
        C'est le plus grand lézard d'Europe et l'un des plus grands d'Espagne, avec
        le lézard géant de Gran Canaria
      metadata_url: https://www.ecologie.gouv.fr/sites/default/files/PNA%20L%C3%A9zard%20Ocell%C3%A9_BAT.pdf
      type: wms_wmts_universal_layer
      params:
        uri: crs=EPSG:2154&featureCount=10&format=image/png&layers=r_pnalezardocelle_s_r76&maxHeight=256&maxWidth=256&styles=&url=https://datacarto.picto-occitanie.fr/wms
        provider: wms

    - title: PNA Maculinéa
      ident: maculinéa
      description: >-
        Phengaris est un genre paléarctique de lépidoptères de la famille
        des Lycaenidae et de la sous-famille des Polyommatinae. Il inclut actuellement
        les espèces précédemment placées dans le genre Maculinea. Ces papillons sont
        connus pour leur cycle de vie complexe, où la chenille doit effectuer une partie
        de son développement à l'intérieur d'une fourmilière
      metadata_url: https://papillons.pnaopie.fr/wp-content/uploads/2021/06/PNA-maculinea.pdf
      type: wms_wmts_universal_layer
      params:
        uri: crs=EPSG:2154&featureCount=10&format=image/png&layers=r_pnamaculinea_s_r76&maxHeight=256&maxWidth=256&styles=&url=https://datacarto.picto-occitanie.fr/wms
        provider: wms

    - title: PNA Milan Royal - Domaines Vitaux en Occitanie
      ident: milan_royal
      description: >-
        Le Milan royal est une espèce de rapaces peuplant l'écozone paléarctique
        occidentale. En ancien français et encore au XVIᵉ siècle, il est appelé escoufle.
      metadata_url: https://www.ecologie.gouv.fr/sites/default/files/PNA-Milan-Royal-2018-2027.pdf
      type: wms_wmts_universal_layer
      params:
        uri: crs=EPSG:2154&featureCount=10&format=image/png&layers=r_pnamilanroyaldv_s_r76ext&maxHeight=256&maxWidth=256&styles=&url=https://datacarto.picto-occitanie.fr/wms
        provider: wms

    - title: PNA Outarde Hivernage
      ident: outarde_hivernage
      description: >-
        Échassier au corps lourd et à fortes pattes, à long cou et à bec court.
      metadata_url: https://www.ecologie.gouv.fr/sites/default/files/PNA_outarde_canepetiere.pdf
      type: wms_wmts_universal_layer
      params:
        uri: crs=EPSG:2154&featureCount=10&format=image/png&layers=r_pnaoutardehi_s_r76&maxHeight=256&maxWidth=256&styles=&url=https://datacarto.picto-occitanie.fr/wms
        provider: wms

    - title: PNA Pie grèche à poitrine rose
      ident: pie_greche_rose
      description: >-
        La Pie-grièche à poitrine rose est une espèce de passereaux aux mœurs
        alimentaires carnassières, appartenant à la famille des Laniidae. Cette pie-grièche
        est considérée en France, au début des années 2010, comme en danger critique.
      metadata_url: https://www.consultations-publiques.developpement-durable.gouv.fr/IMG/pdf/PNA_Lanius_2014-2018.pdf
      type: wms_wmts_universal_layer
      params:
        uri: crs=EPSG:2154&featureCount=10&format=image/png&layers=r_pnapiegrecheapoitrinerose_s_r76&maxHeight=256&maxWidth=256&styles=&url=https://datacarto.picto-occitanie.fr/wms
        provider: wms

    - title: PNA Pie-Grièche Grise
      ident: pei-greche_grise
      description: >-
        La Pie-grièche grise est une espèce d'oiseaux de la famille des
        Laniidae. Elle niche en Europe méridionale et en Afrique du Nord. La forme migratrice
        est quelquefois visible en Europe occidentale
      metadata_url: https://www.consultations-publiques.developpement-durable.gouv.fr/IMG/pdf/PNA_Lanius_2014-2018.pdf
      type: wms_wmts_universal_layer
      params:
        uri: crs=EPSG:2154&featureCount=10&format=image/png&layers=r_pnapiegriechegrise_s_r76&maxHeight=256&maxWidth=256&styles=&url=https://datacarto.picto-occitanie.fr/wms
        provider: wms

    - title: PNA Pie-Grièche Méridionale
      ident: pie_greche_meridionale
      description: >-
        La Pie-grièche méridionale (Lanius meridionalis) est une espèce
        d''oiseaux de la famille des Laniidae. Elle niche en Europe méridionale et en
        Afrique du Nord. La forme migratrice est quelquefois visible en Europe occidentale
      metadata_url: https://www.consultations-publiques.developpement-durable.gouv.fr/IMG/pdf/PNA_Lanius_2014-2018.pdf
      type: wms_wmts_universal_layer
      params:
        uri: crs=EPSG:2154&featureCount=10&format=image/png&layers=r_pnapiegriechemeridionale_s_r76&maxHeight=256&maxWidth=256&styles=&url=https://datacarto.picto-occitanie.fr/wms
        provider: wms

    - title: PNA Pie-Grièche à Tête Rousse
      ident: pie_greche_rousse
      description: >-
        Les Laniidés sont des passereaux de taille petite à moyenne, au corps allongé, à ailes arrondies et à queue longue
      metadata_url: https://www.consultations-publiques.developpement-durable.gouv.fr/IMG/pdf/PNA_Lanius_2014-2018.pdf
      type: wms_wmts_universal_layer
      params:
        uri: crs=EPSG:2154&featureCount=10&format=image/png&layers=r_pnapiegriecheteterousse_s_r76&maxHeight=256&maxWidth=256&styles=&url=https://datacarto.picto-occitanie.fr/wms
        provider: wms

    - title: PNA Placette d'alimentation nécrophage
      ident: placette
      description: >-
        Mise en place de placettes de dépôt de cadavres de bétail, naturellement
        mort en exploitation, en vue de l''équarrissage naturel par ces rapaces nécrophages
        en zone de montagne
      metadata_url: https://www.ecologie.gouv.fr/sites/default/files/PNA_Vautour_fauve_2017-2026.pdf
      type: wms_wmts_universal_layer
      params:
        uri: crs=EPSG:2154&featureCount=10&format=image/png&layers=r_pnaplacettealimentationnecrophage_s_r76ext&maxHeight=256&maxWidth=256&styles=&url=https://datacarto.picto-occitanie.fr/wms
        provider: wms

    - title: PNA Sonneur à ventre jaune – Zone de présence du sonneur à ventre jaune
      ident: sonneur_ventre_jaune
      description: >-
        Bombina variegata est une espèce d'amphibiens de la famille des Bombinatoridae.
        Il est appelé en français Sonneur à ventre jaune ou Crapaud sonneur à ventre
        jaune ou Sonneur à pieds épais.
      metadata_url: https://www.ecologie.gouv.fr/sites/default/files/PNA_Sonneur-a-ventre-jaune_2011-2015.pdf
      type: wms_wmts_universal_layer
      params:
        uri: crs=EPSG:2154&featureCount=10&format=image/png&layers=r_pnasonneuraventrejaune_s_r76&maxHeight=256&maxWidth=256&styles=&url=https://datacarto.picto-occitanie.fr/wms
        provider: wms

    - title: PNA Vautour Fauve - Domaines Vitaux
      ident: vautour_fauve
      description: >-
        Le Vautour fauve, ou anciennement le griffon, est une espèce d'oiseaux
        charognard de la famille des Accipitridae
      metadata_url: https://www.ecologie.gouv.fr/sites/default/files/PNA_Vautour_fauve_2017-2026.pdf
      type: wms_wmts_universal_layer
      params:
        uri: crs=EPSG:2154&featureCount=10&format=image/png&layers=r_pnavautourfauvedv_s_r76ext&maxHeight=256&maxWidth=256&styles=&url=https://datacarto.picto-occitanie.fr/wms
        provider: wms

    - title: PNA Vautour Percnoptère - Domaines Vitaux
      ident: vautour_percnotère
      description: >-
        Le Vautour percnoptère, aussi appelé Percnoptère d'Égypte, est une
        espèce de rapaces de l'Ancien Monde.
      metadata_url: https://www.ecologie.gouv.fr/sites/default/files/PNA_Vautour-percnoptere_2015-2024.pdf
      type: wms_wmts_universal_layer
      params:
        uri: crs=EPSG:2154&featureCount=10&format=image/png&layers=r_pnapercnoptere_s_r76ext&maxHeight=256&maxWidth=256&styles=&url=https://datacarto.picto-occitanie.fr/wms
        provider: wms