---
title: Couches Vector Tiles
ident: 
description: 
type: folder
children:
  
  - title: ADMINEXPRESS Vector Tiles
    ident: adminexpress_vectortiles
    description: 
    metadata_url: 
    type: vector_layer
    params:
      url: https://wxs.ign.fr/essentiels/geoportail/tms/1.0.0/ADMIN_EXPRESS/%7Bz%7D/%7Bx%7D/%7By%7D.pbf
  
  - title: Plan IGN Vector Tiles
    ident: plan_ign_vectortiles
    description: 
    metadata_url: 
    type: vector_layer
    params:
      url: https://wxs.ign.fr/essentiels/geoportail/tms/1.0.0/PLAN.IGN/{z}/{x}/{y}.pbf
  
  - title: BD TOPO Vector Tiles
    ident: bdtopo_vectortiles
    description: 
    metadata_url: 
    type: vector_layer
    params:
      url: https://wxs.ign.fr/essentiels/geoportail/tms/1.0.0/topographie/{z}/{x}/{y}.pbf
